#!/usr/bin/env bash

mc_port=25566
port=${1:-${PORT:-8080}}

if [ -z "$NGROK_API_TOKEN" ]; then
  echo "You must set the NGROK_API_TOKEN config var to create a TCP tunnel!"
  exit 1
fi

ngrok_cmd="bin/ngrok -authtoken $NGROK_API_TOKEN -log stdout ${NGROK_OPTS} -proto=tcp ${mc_port}"
echo "Starting: ngrok"
eval "$ngrok_cmd &"
ngrok_pid=$!

# create server config
echo "server-port=${mc_port}" > /app/server.properties

limit=$(ulimit -u)
case $limit in
  512)   # 2X Dyno
  heap="768m"
  ;;
  32768) # PX Dyno
  heap="4g"
  ;;
  *)     # 1X Dyno
  heap="384m"
  ;;
esac

echo "Starting: minecraft ${mc_port}"
eval "java -Xmx${heap} -Xms${heap} -jar minecraft.jar nogui &"
main_pid=$!

# echo "Starting: web"
# eval "ruby -rwebrick -e'WEBrick::HTTPServer.new(:Port => ${port}, :DocumentRoot => Dir.pwd).start' &"
# web_pid=$!

trap "kill $ngrok_pid $main_pid $web_pid" SIGTERM
trap "kill -9 $ngrok_pid $main_pid $web_pid; exit" SIGKILL

# sleep 10
#
# while kill -0 $main_pid
# do
#   sleep 2000
# done

ruby -rwebrick -e'WEBrick::HTTPServer.new(:Port => ${port}, :DocumentRoot => Dir.pwd).start' 
