#!/usr/bin/env bash

if [ -n "$AWS_BUCKET" ] && [ -d world ]; then
  cat << EOF > .s3cfg
[default]
access_key = ${AWS_ACCESS_KEY}
secret_key = ${AWS_SECRET_KEY}
EOF

  s3cmd sync world/ s3://${AWS_BUCKET}/world/ < /dev/null 2>&1

  rm .s3cfg
fi
